### ISSUE TITLE
Updates about README

### ISSUE THREAD

**Issue by Desperado721** [PLXIV/Gebiotoolkit#1]
Hi, 
I am interested in this toolkits. It's super cool. However I am not quite sure about how to use it. Could you update the README part? Thank you

**Comment by PLXIV** [comment]
Hey thanks for the interest. 

Right now I am working on other projects so I do not have that much time to update it the state of this project saddly.

However, you can send me an email (lilin.pau@gmail.com) and I will provide you support whenever possible.
